### ISSUE TITLE
Fatal Error :: FATA[0075] Failed to check DTR bootstrapper image version

### ISSUE THREAD

**Issue by pjmcquade** [Mirantis/launchpad_legacy#55] opened 2020-10-22 20:18 UTC
Hello Folks,

Thanks so much for the fix for #52.  There's a new one now.  

```
sh-4.2# ./launchpad-linux-x64 version
version: 1.0.2
commit: ad58f68
```

Here's my cluster.yml file (datamasked):

```
# API version: launchpad.mirantis.com/v1
# Ansible managed
# Source: https://bitbucket.example.com/projects/EIU/repos/ei-unix-docker-ee-playbooks/browse
# Launchpad Sales Pitch: https://www.mirantis.com/blog/mirantis-launchpad-quick-start/
# Launchpad Source: https://github.com/Mirantis/launchpad/
#
# flags for the installer are displayed via:
# docker run -t -i --rm docker/ucp:3.3.0 install --help
#


apiVersion: launchpad.mirantis.com/v1
kind: DockerEnterprise
metadata:
  name: lab-unix-ucp-ca.example.com
spec:

  dtr:
    version: 2.8.0
    #imageRepo: "docker.io/docker"
    imageRepo: "lab-unix-dtr-ca.example.com/unixinfra"
    replicaConfig: sequential # we install sequentially to adhere to the install primary, then install the replicas pattern
    installFlags:
      - --dtr-external-url lab-unix-dtr-ca.example.com
      - --ucp-username=ucpadmin
      - --ucp-password=[REDACTED]
      - --ucp-url lab-unix-ucp-ca.example.com
      - --ucp-ca "$(curl -k -s https://lab-unix-ucp-ca.example.com:443/ca)"
      - --replica-http-port 80
      - --replica-https-port 443
      - --http-proxy proxy-mwg-http.example.com:8080
      - --https-proxy proxy-mwg-http.example.com:8443
      - --no-proxy localhost,127.0.0.1,10.*,172.*,192.*,159.*,example.com
      - --debug
      - --dtr-ca "$(cat /root/docker_install/dtr-ca.pem)"
      - --dtr-cert "$(cat /root/docker_install/dtr-cert.pem)"
      - --dtr-key "$(cat /root/docker_install/dtr-key.pem)"

  ucp:
    version: 3.3.3
    #imageRepo: "docker.io/docker"
    imageRepo: "lab-unix-dtr-ca.example.com/unixinfra"
    installFlags:
      - --admin-username=ucpadmin
      - --admin-password=[REDACTED]
      - --secure-overlay
      - --default-node-orchestrator=kubernetes
      - --san lab-unix-ucp-ca.example.com
      - --skip-cloud-provider-check
      - --force-minimums
      - --external-server-cert
      - --disable-tracking
      - --disable-usage
      - --debug
      - --license '{REDACTED}'
    configData: |-
      [auth]
        backend = "ldap"
      [scheduling_configuration]
        default_node_orchestrator = "kubernetes"
        enable_admin_ucp_scheduling = true
      [cluster_config]
        ipip_mtu = "1356"
        calico_mtu = "1356"
        secure_overlay = true

  engine:
    version: 19.03.8
    installURLLinux: file:////root/docker_install/example-customized-ucp-install.sh

  hosts:
  ############
  # managers #
  ############
  - address: host660.example.com
    sshPort: 22
    user: root
    # sshKeyPath: ~/.ssh/launchpad_rsa
    ssh:
      user: root
      port: 22
      keyPath: ~/.ssh/launchpad_rsa
    role: manager
  - address: host661.example.com
    sshPort: 22
    user: root
    # sshKeyPath: ~/.ssh/launchpad_rsa
    ssh:
      user: root
      port: 22
      keyPath: ~/.ssh/launchpad_rsa
    role: manager
  - address: host662.example.com
    sshPort: 22
    user: root
    # sshKeyPath: ~/.ssh/launchpad_rsa
    ssh:
      user: root
      port: 22
      keyPath: ~/.ssh/launchpad_rsa
    role: manager

  ###########
  # workers #
  ###########

  - address: host663.example.com
    sshPort: 22
    user: root
    # sshKeyPath: ~/.ssh/launchpad_rsa
    ssh:
      user: root
      port: 22
      keyPath: ~/.ssh/launchpad_rsa
    role: worker
  - address: host664.example.com
    sshPort: 22
    user: root
    # sshKeyPath: ~/.ssh/launchpad_rsa
    ssh:
      user: root
      port: 22
      keyPath: ~/.ssh/launchpad_rsa
    role: worker
  - address: host665.example.com
    sshPort: 22
    user: root
    # sshKeyPath: ~/.ssh/launchpad_rsa
    ssh:
      user: root
      port: 22
      keyPath: ~/.ssh/launchpad_rsa
    role: worker

  ###########
  #  dtrs   #
  ###########

  - address: host666.example.com
    sshPort: 22
    user: root
    # sshKeyPath: ~/.ssh/launchpad_rsa
    ssh:
      user: root
      port: 22
      keyPath: ~/.ssh/launchpad_rsa
    role: dtr
  - address: host667.example.com
    sshPort: 22
    user: root
    # sshKeyPath: ~/.ssh/launchpad_rsa
    ssh:
      user: root
      port: 22
      keyPath: ~/.ssh/launchpad_rsa
    role: dtr
  - address: host668.example.com
    sshPort: 22
    user: root
    # sshKeyPath: ~/.ssh/launchpad_rsa
    ssh:
      user: root
      port: 22
      keyPath: ~/.ssh/launchpad_rsa
    role: dtr
```

When I execute it via: ``./launchpad-linux-x64 --debug --disable-telemetry apply --config cluster.yml | tee test-new-launchpad.log``

Everything appears to ok except for the last line:

```
INFO[0073] ==> Running phase: Upgrade DTR components
DEBU[0073] host666.example.com: found DTR installed, using as leader
DEBU[0073] analytics disabled, not tracking event 'Upgrade DTR components'
INFO[0073] See /root/.mirantis-launchpad/cluster/lab-unix-ucp-ca.example.com/apply.log for more logs
DEBU[0073] analytics disabled, not tracking event 'Cluster Apply Failed'
FATA[0075] Failed to check DTR bootstrapper image version
```

Any thoughts?

Thanks!
-Patrick

**Comment by kke** [comment] 2020-10-27 06:58
Duplicate of #54

**Closed as completed by kke** 2020-10-27 06:58 UTC

**Comment by kke** [comment] 2020-10-30 11:12
Fixed in https://github.com/Mirantis/launchpad/releases/tag/1.0.3
